# This file was generated by GoReleaser. DO NOT EDIT.
cask "harness-cli" do
  version "3.7.1"

  on_macos do
    on_arm do
      sha256 "e3419a2858066737923c3466fa679a9a4f4d2c211b718c684a77a73e36163ffd"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f6b8c858dd4212560159ea0c4c700333bdd113ef75bfb4bc2ca87b0db93e8170"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d3b4498ea196fc4b5b755902d95699ae091340066ab3e163d06efd37ee0057b7"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c8700f4fed03a8d313cb51f3b40b6aad297809ebd73f0d2ca094ddb8cb19ad7"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_linux_amd64.tar.gz"
    end
  end

  name "harness-cli"
  desc "Harness Unified CLI"
  homepage "https://harness.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harness"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/harness"]
    end
    system_command "#{staged_path}/harness",
                   args: ["--post-install"],
                   env: { "HARNESS_INSTALL_TYPE" => "brew" },
                   must_succeed: false
  end

  # No zap stanza required
end
