# This file was generated by GoReleaser. DO NOT EDIT.
cask "harness-cli" do
  version "3.9.0"

  on_macos do
    on_arm do
      sha256 "cc579622d15da33e61b2c948692b24017c076b7772c841b5b216eae56f9ce46e"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0b119b31e0d59609d568e8b1903ad223f84462d594272f711560d7e4867d7cf"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7ff6211fb2e5d137dfed8c6b1ce1f2b3826458b48aaa6e3105f7c25062bafe02"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "48c3b537af8c1f9a02e823a5b332dc3aeda130f4844ea3631b6eb6fe5b8f2b01"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_linux_amd64.tar.gz"
    end
  end

  name "harness-cli"
  desc "Harness Unified CLI"
  homepage "https://harness.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harness"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/harness"]
    end
    system_command "#{staged_path}/harness",
                   args: ["--post-install"],
                   env: { "HARNESS_INSTALL_TYPE" => "brew" },
                   must_succeed: false
  end

  # No zap stanza required
end
