# This file was generated by GoReleaser. DO NOT EDIT.
cask "harness-cli" do
  version "3.6.0"

  on_macos do
    on_arm do
      sha256 "5d3985fc3bf7d32a669a603a2bf0b3b7aca1f69eb42b0454e33150ae31ddf44e"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "051dfaafbaed8660f6c7f06fbc484cef1b5dc4f7932b39bd6583f32dd6ef3a56"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "568d77c122f79a2e3236b4b110f09c76e37d0def998be023f467ca8e6ce18dc0"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8ffec2578eae2969ed841722209d8470ef4b49ab5f7cc2644b2bd816ad23a93"
      url "https://github.com/harness/cli/releases/download/v#{version}/harness-core_#{version}_linux_amd64.tar.gz"
    end
  end

  name "harness-cli"
  desc "Harness Unified CLI"
  homepage "https://harness.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harness"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/harness"]
    end
    system_command "#{staged_path}/harness",
                   args: ["--post-install"],
                   env: { "HARNESS_INSTALL_TYPE" => "brew" },
                   must_succeed: false
  end

  # No zap stanza required
end
